### ISSUE TITLE
any updates for the mid-level research list?

### ISSUE THREAD

**Issue by ShreevathsaGP** [Kennyslaboratory/Hacker-Heaven#1]
You mentioned that the mid-level readme was subject to change as you improved. How's it going?

**Comment by Kennyslaboratory** [comment]
Thanks for reaching out!  Yeah, I can probably add another thing or two but
based on my experience getting a job doing application testing, most of
that stuff is spot on.  I could add a few more Mobile Application stuff.

The idea of the roadmap is to keep everything simplified to the most
important things you need to know in order to land the job.

**Comment by ShreevathsaGP** [comment]
alright man, thanks for the quick response.
